spring:
    cache:
        type: hazelcast
    main:
        web-environment: false


server:
    port: 6000

application:
    cache:
        hazelcast:
              group-name: name
              group-pass: pass
              network:
                  enabled-multicast: true
              management-center:
                  enable: false
                  update-interval: 3
                  url: http://localhost:6000/mancenter